version: '3'

services:
### PHP-FPM ##############################################
    php-fpm:
      build:
        context: .
        dockerfile: ./docker/php-fpm/Dockerfile-production
        # args:
        #   - LARADOCK_PHP_VERSION=${PHP_VERSION}
      expose:
        - "9000"

### NGINX Server #########################################
    nginx:
      build:
        context: .
        dockerfile: ./docker/nginx/Dockerfile-production
      ports:
        - "80:80"
        - "443:443"
      depends_on:
        - php-fpm

